### ISSUE TITLE
Different code in maven central

### ISSUE THREAD

**Issue by luismora1224** [jmapper-framework/jmapper-core#105]
Hello

A few days ago I was working on a project that uses the jmapper-core dependency, however I was surprised that when I updated a library called XStream to version 1.4.19, the project started to crash, investigating the issue I found that the jmapper-core repository It was left without support since 2016, however I found that precisely, you created a fork of the project and made the necessary updates, to solve this problem and the vulnerabilities that the project brought, only that I had a doubt, and it is that I see that you fork has version 1.6.1.CR2, and when using the maven dependency with that same version it brings me the old code (the one from 2016) and not its current code, do you know why?

Thank you very much for your reply, I look forward to it.
Greetings.

**Comment by Shryne** [comment]
As far as I know, there was no fork. This project started at googlecode and moved to github, but I think that's all.

The last release of this project was in 2016 (see under releases here in github). However, the github dependency checker complained about some vulnerabilities and added some pull requests, which have been accepted by the author. 
This leads to your findings: The master branch is ahead of the maven code, because it hasn't been released.

If you want the new code, you can try it with https://jitpack.io/ (explicitly choose the branches or commits).

**Comment by luismora1224** [comment]
I understand, according to your answer do you think there is a possibility that the current code will be deployed in maven at some point?

**Comment by Shryne** [comment]
I don't think so. The author has stated that he doesn't want to continue working on this project.

**Comment by luismora1224** [comment]
ok thank you very much for your answer.
